!java_agent.

+!java_agent : true <-
    // Add your code here for creating a "Counter" object using the **default** constructor...
    // ... Then call the "increment" method after that the "getCount" one...
    // ... And finish printing the value you got from the "getCount" method.
    // Add your code here for creating a "Counter" object using the constructor **taking one argument**...
    // ... Then call the "increment" method after that the "getCount" one...
    // ... And finish printing the value you got from the "getCount" method.
    // Add your code here for calling the **static** method in the "Counter" class ...
    // ... And finish printing the string you got from that method.

{ include("$jacamoJar/templates/common-cartago.asl") }
